version: "3.1"

services:
  db:
    build: ./docker/postgres/
    volumes:
      - data:/var/lib/postgresql/data
      - ./docker/postgres/data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: octopush
      POSTGRES_USER: _octopush
      POSTGRES_PASSWORD: password

  app:
    build: ./docker/nodejs/
    ports:
      - 80:3000
      - 9229:9229
    depends_on:
      - db
    volumes:
      - .:/var/www/octopush

volumes:
  data:
