postgres:
  build: ./docker/postgres/
  expose:
    - 5432
  volumes_from:
    - data
  volumes:
    - ./docker/postgres/data:/docker-entrypoint-initdb.d
  environment:
    POSTGRES_DB: octopush
    POSTGRES_USER: _octopush
    POSTGRES_PASSWORD: password

nodejs:
  build: ./docker/nodejs/
  ports:
    - 80:3001
    - 9229:9229
  links:
    - postgres
  volumes:
    - .:/var/www/octopush

data:
  image: node:latest
  volumes:
    - /var/lib/postgresql/data
  command: "true"
